language: python
python:
  - "3.5"
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=flake8
    # added ppc64le arch.
    - TOXENV=py27
      arch: ppc64le
    - TOXENV=py32
      arch: ppc64le
    - TOXENV=py33
      arch: ppc64le
    - TOXENV=py34
      arch: ppc64le
    - TOXENV=py35
      arch: ppc64le
    - TOXENV=pypy
      arch: ppc64le
    - TOXENV=pypy3
      arch: ppc64le
    - TOXENV=flake8install:
  - travis_retry pip install tox
script:
  - make test
